# 机器人配置文件
#################################

velLine : 5           # 界面点动限速：平移(毫米)
velRotate : 0.5		  # 界面点动限速：旋转(度)

CYLINDER_INDEX : 5		# 推杆关节轴号索引
STEER_LEFT_INDEX : 11	# 左舵轮索引
STEER_RIGHT_INDEX : 13	# 右舵轮索引
WHEEL_LEFT_INDEX : 12	# 左行走轮索引
WHEEL_RIGHT_INDEX : 14	# 右行走轮索引
TOOL_LIFTING: 9			# 工具升降索引

Lift_Distance_In_Parallel : 90.0	# 调平状态下举升的位置
Max_Deviation_In_Parallel : 50.0	# 调平允许最大偏差
Min_Deviation_In_Parallel : 5.0		# 调平允许最小偏差

Distance_work : 90					# 位置

Lift_Distance_In_FitBoard : 6.0     # 贴合状态下举升的位置
Max_Deviation_In_FitBoard : 20.0    # 贴合允许偏差
Min_Deviation_In_FitBoard : 6.0     # 贴合允许偏差

Line_Deviation_Threshold : 2.0		# 边线调整允许偏差

#################################

# 关节末端运动限速
end_vel_limit: [5,5,5,0.05,0.05,0.05]
end_vel_position: [1,1,1,0.05,0.05,0.05]

# 准备位置(装板)
home_point: [2.21, -0.25, 1.84, 10, 76.41, 817.17, 1142.71, 1.86, -4.23, 901.36 , 561.06]
# 举升位置(装板)
prepare_point: [97.45, 46.27, 11.63, 9.75, 78.81, 1043.36, 1194.38, 0.55, -62.84, 885.0 , 554.58]

# 准备位置(碰钉)
# home_point: [16.020,-90,0,10.23,76,801, 1095, 0, -12, 1109]
# 举升位置(碰钉)
# prepare_point: [16.02,-30,0,10.23,76.01,1034.45,1177.37, 0.8, -71.17, 1162.56]

# 机器人下位机IP和端口
robot_ip: "192.168.1.130"
robot_port: 6999

IOA_ip: "192.168.1.201"
IOA_port: 5999