title: "####################--Robot'configuration--##################"
line0: "#############################################################"
velLine:
  brief: 界面点动限速：平移(毫米)
  value: 1
velRotate:
  brief: 界面点动限速：旋转(度)
  value: 0.05
end_vel_limit:
  brief: 关节运动限速
  value: [2, 2, 2, 0.05, 0.05, 0.05]
end_vel_position:
  brief: 末端运动限速
  value: [1, 1, 1, 0.05, 0.05, 0.05]
line1: "#############################################################"
CYLINDER_INDEX:
  brief: 推杆关节轴号索引
  value: 5
STEER_LEFT_INDEX:
  brief: 左舵轮索引
  value: 11
STEER_RIGHT_INDEX:
  brief: 右舵轮索引
  value: 13
WHEEL_LEFT_INDEX:
  brief: 左行走轮索引
  value: 12
WHEEL_RIGHT_INDEX:
  brief: 右行走轮索引
  value: 14
TOOL_LIFTING:
  brief: 工具升降索引
  value: 9
Lift_Distance_In_Parallel:
  brief: 调平状态下举升的位置
  value: 90.0
Max_Deviation_In_Parallel:
  brief: 调平允许最大偏差
  value: 50.0
Min_Deviation_In_Parallel:
  brief: 调平允许最小偏差
  value: 5.0
Distance_work:
  brief: 位置
  value: 90
Lift_Distance_In_FitBoard:
  brief: 贴合状态下举升的位置
  value: 6.0
Max_Deviation_In_FitBoard:
  brief: 贴合允许最大偏差
  value: 20.0
Min_Deviation_In_FitBoard:
  brief: 贴合允许最小偏差
  value: 6.0
Line_Deviation_Threshold:
  brief: 边线调整允许偏差
  value: 1.0
Second_Push_Distance:
  brief: 二次举升目标位置
  value: 200.0
Second_Quit_Distance:
  brief: 二次退出目标位置
  value: 100.0
Vision_Replace_1_Offset:
  brief: 替换视觉数据1
  value: 15
Vision_Replace_3_Offset:
  brief: 替换视觉数据1
  value: 15
Vision_Replace_4_Offset:
  brief: 替换视觉数据1
  value: 15
Vision_Replace_5_Offset:
  brief: 替换视觉数据1
  value: 15
line2: "#############################################################"
prepare_position:
  brief: 准备位置(装板)
  value:
    - -2.4414062500000001e-05
    - 7.9472859700520837e-07
    - 0.02476811408996582
    - -0.0015000768749360766
    - 81.965804200423392
    - 790.02667733601163
    - 1169.5822448730469
    - 0.52688100004562399
    - 8.1973388571488233
    - 885.00010426839196
    - 561.57883645466393
    - 7.9543603207155522
    - 0.00010510210815557541
    - 7.9541538394460192
    - -0.00011757184980115215
lift_position:
  brief: 举升位置(装板)
  value:
    - 11.521994018554688
    - 0.0016880035400390625
    - -0.018449624379475914
    - 0.75183746204758795
    - 90.000284897653685
    - 1052.3598657335554
    - 1091.9900716145833
    - -1.0432747161106757
    - 56.112540295249538
    - 964.74315643310547
    - 561.57876697267795
    - 5.8447262410287308
    - -5652.8841398246705
    - 5.844726552463527
    - 5726.8715669242529
line3: "#############################################################"
robot_ip:
  brief: 机器人下位机IP
  value: 192.168.1.130
robot_port:
  brief: 机器人下位机端口
  value: 6999
IOA_ip:
  brief: IOA板IP
  value: 192.168.1.201
IOA_port:
  brief: IOA板端口
  value: 5999
line4: "#############################################################"